### ISSUE TITLE
leading whitespace

### ISSUE THREAD

**Issue by freasy** [unjs/destr#21] opened 2022-11-24 12:10 UTC
TL;DR: After updating "a" laravel package our app broke because destr evaluates all responses as string.

We are using lates laravel as backend with a fairly new plain vue3 frontend.

We are using ofetch (former ohmyfetch) for fetching api responses.
After a update laravel resources responses now have a leading whitespace, thats the reason destr evaluates the response as a string.

How to reproduce:
```javascript
destr('{}') // type object
destr(' {}') // type text
```

Is is possible to trim the data before try parsing it?

**Comment by NozomuIkuta** [comment] 2022-11-27 16:47
[RFC8259](https://www.rfc-editor.org/rfc/rfc8259) says that JSON text is a "value" optionally surrounded by white spaces (Section 2: JSON Grammer).

So, `' {}'` should be parsed as a valid JSON, and actually `JSON.parse()` returns an object.

If I'm correct, the root cause is the regular expression below.

https://github.com/unjs/destr/blob/6fb4e9203d0967cac69a273c8f88e4ab38c3aa60/src/index.ts#L6

It should accept white spaces.

I could fix the bug quickly, but it seems that we need unit tests first, otherwise we can't verify the bug fix.

**Comment by NozomuIkuta** [comment] 2022-12-02 14:08
Sorry,this issue was closed against my will, because I happened to use GitHub's magic comment in the PR (i.e., "fix #number).🙌

Let me reopen this issue and I will submit a PR to really fix this issue.

**Comment by pi0** [comment] 2022-12-05 11:56
Fixed in 639a5df5321d9dccc05ccc1489f75ff8c4c57981 (sorry @NozomuIkuta quickly added fix for next release)

**Closed** 2022-12-05 11:56 UTC
